#!/usr/bin/env python

import sys, os, time

args = " 100 0.0 0.0 0.0 -1 false"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_0_0_0")
  time.sleep(1)

"""
args = " 100 0.0 0.005 0.0 -1 false" 
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_point_five_0_0")
  time.sleep(1)

args = " 100 0.0 0.01 0.0 -1 false"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_one_0_0")
  time.sleep(1)

args = " 100 0.0 0.04 0.7 -1 false"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_four_seven_0_0")
  time.sleep(1)

args = " 100 0.0 0.08 0.7 -1 false"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_eight_seven_0_0")
  time.sleep(1)

args = " 100 0.0 0.005 0.0 -1 true"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_point_five_0_1")
  time.sleep(1)

args = " 100 0.0 0.01 0.0 -1 true"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_one_0_1")
  time.sleep(1)

args = " 100 0.0 0.04 0.7 -1 true"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_four_seven_0_1")
  time.sleep(1)

args = " 100 0.0 0.08 0.7 -1 true"
for i in range (0, 10):
  os.system("./d2test "+args + " >> result/100_eight_seven_0_1")
  time.sleep(1)
"""
