#!/usr/bin/env python

import sys, os

os.system("scp ../src/deetoomessage.cpp ../src/deetoomessage.h ../src/deetoonetwork.cpp ../src/deetoonetwork.h ../src/MapReduceTask.cpp ../src/MapReduceTask.h kyungyong@c9node2.acis.ufl.edu:Documents/SourceCode/netmodeler/src/")
os.system("scp d2test.cpp kyungyong@c9node2.acis.ufl.edu:Documents/SourceCode/netmodeler/test/")
